Repository JamesPartsafas/online-store, pull requests merged in 2022-02, with the labels that each got.

#69 Created skeleton code for homepage
  amaznot/public/assets/amaznot.ico
  amaznot/public/assets/amaznot.png
  amaznot/public/assets/amaznot_full.png
  amaznot/public/css/styles.css
  amaznot/public/js/script.js
  amaznot/resources/views/layouts/layout.blade.php
  amaznot/resources/views/pages/index.blade.php
Labels: Frontend

#70 Made a login check & Admin account check
  amaznot/app/Http/Controllers/LoginController.php
Labels: Backend

#76 Fixed User Registration Problem
  amaznot/app/Http/Controllers/RegisterController.php
  amaznot/app/Models/User.php
  amaznot/resources/views/auth/login.blade.php
Labels: bug, Backend

#83 #82 Place yml file in proper directory
  .github/workflows/laravel.yml
Labels: bug, DevOps

#79 Created signup frontend page
  amaznot/resources/views/auth/register.blade.php
Labels: Frontend, Core Feature

#85 #74 Generate HTTPS links by default in production
  amaznot/app/Providers/AppServiceProvider.php
  amaznot/resources/views/auth/register.blade.php
Labels: bug, DevOps

#84 Created aisles page for frontend
  amaznot/app/Http/Controllers/ListController.php
  amaznot/public/css/styles.css
  amaznot/resources/views/pages/productlist.blade.php
  amaznot/routes/web.php
Labels: Frontend

#90 #89 Handle cart functionality on the product page
  amaznot/app/Http/Controllers/ProductController.php
  amaznot/database/seeders/ProductSeeder.php
  amaznot/public/js/script.js
  amaznot/resources/views/layouts/layout.blade.php
  amaznot/resources/views/pages/productpage.blade.php
Labels: Frontend

#99 #95 Implement backend routing to the cart page and a skeleton for the…
  amaznot/app/Http/Controllers/CartController.php
  amaznot/public/css/styles.css
  amaznot/resources/views/pages/cart.blade.php
  amaznot/routes/web.php
Labels: Backend

#100 #78 added admin add product page (frontend)
  amaznot/package-lock.json
  amaznot/resources/views/pages/admin/addproduct.blade.php
Labels: Frontend

#97 #53-create-frontend-layout
  amaznot/app/Models/User.php
  amaznot/app/Providers/AppServiceProvider.php
  amaznot/app/Providers/HeaderStaticData.php
  amaznot/public/css/styles.css
  amaznot/public/js/script.js
  amaznot/resources/views/layouts/layout.blade.php
Labels: Frontend, Backend

#102 #56 Aisles Page
  amaznot/app/Http/Controllers/ListController.php
Labels: Frontend

#104 #98 fixing bugs on homepage
  amaznot/public/css/styles.css
  amaznot/public/js/script.js
  amaznot/resources/views/layouts/layout.blade.php
  amaznot/resources/views/pages/index.blade.php
  amaznot/resources/views/pages/productpage.blade.php
Labels: bug, Frontend

#108 #93 Track user purchases
  amaznot/app/Http/Controllers/OrderController.php
  amaznot/app/Models/Order.php
  amaznot/app/Models/OrderItem.php
  amaznot/database/migrations/2022_02_19_182156_create_orders_table.php
  amaznot/database/migrations/2022_02_19_194037_create_order_items_table.php
  amaznot/resources/views/pages/cart.blade.php
  amaznot/resources/views/pages/orders.blade.php
  amaznot/routes/web.php
Labels: Backend, Database
