Repository JamesPartsafas/online-store, pull requests merged in 2022-03, with the labels that each got.

#114 Bugfix for description not displaying correctly
  amaznot/resources/views/pages/productpage.blade.php
Labels: bug, Frontend

#112 #91 Backend for Order is setup
  .github/workflows/laravel.yml
  amaznot/app/Http/Controllers/LoginController.php
  amaznot/app/Http/Controllers/OrderController.php
  amaznot/app/Http/Controllers/ProductController.php
  amaznot/app/Models/Order.php
  amaznot/app/Models/OrderItem.php
  amaznot/app/Models/Product.php
  amaznot/resources/views/pages/orders.blade.php
  amaznot/resources/views/pages/ordersitems.blade.php
  amaznot/routes/web.php
Labels: Backend

#119 Created disclaimer page
  amaznot/app/Http/Controllers/HomeController.php
  amaznot/resources/views/layouts/layout.blade.php
  amaznot/resources/views/pages/disclaimer.blade.php
  amaznot/resources/views/pages/index.blade.php
  amaznot/routes/web.php
Labels: enhancement, Frontend

#124 117 contact us page
  amaznot/public/css/styles.css
  amaznot/resources/views/layouts/layout.blade.php
  amaznot/resources/views/pages/contactus.blade.php
Labels: enhancement, Frontend

#125 #96-add-order-history-page
  amaznot/public/css/styles.css
  amaznot/public/js/script.js
  amaznot/resources/views/layouts/layout.blade.php
  amaznot/resources/views/pages/orders.blade.php
  amaznot/resources/views/pages/ordersitems.blade.php
Labels: Frontend

#123 111 finish the cart page
  README.md
  amaznot/public/js/script.js
  amaznot/resources/views/pages/cart.blade.php
  amaznot/resources/views/pages/productpage.blade.php
Labels: Frontend

#127 #121 Made Version 1 of Fuzzy Search
  amaznot/app/Http/Controllers/SearchController.php
  amaznot/resources/views/pages/search.blade.php
  amaznot/routes/web.php
  amaznot/tests/Feature/SearchTest.php
Labels: Backend
